# This is a basic workflow to help you get started with Actions

name: Production deploy CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: Cache node
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        path: |
          ~/.npm

    - name: Dry run build
      env:
        VUE_APP_GRAPHQL_API: ${{ secrets.VUE_APP_GRAPHQL_API }}
        VUE_APP_SENTRY: ${{ secrets.VUE_APP_SENTRY }}
      run: |
        npm ci
        npm run build --report
        mv ./dist/report.html ./report.html

    - name: Upload to server
      uses: appleboy/scp-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        target: ${{ format("/web/hackthe6ix/{0}", GITHUB_SHA) }}
        source: "dist/*"
        strip_components: 1

    - name: Deploy artifact
      uses: appleboy/ssh-action@master
      env:
          HASH: ${{ GITHUB_SHA }}
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        envs: HASH
        script: |
          cd /web/production
          ln -s ../hackthe6ix/$HASH hackthe6ix
