# This is a basic workflow to help you get started with Actions

name: Production deploy CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
  
    - name: Cache node
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        path: |
          ~/.npm

    - name: Dry run build
      env:
        VUE_APP_GRAPHQL_API: ${{ secrets.VUE_APP_GRAPHQL_API }}
        VUE_APP_SENTRY: ${{ secrets.VUE_APP_SENTRY }}
      run: |
        npm ci
        npm run build
    
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "dist/*"
        target: "/web/hackthe6ix"
